# Generated by Django 5.1.2 on 2025-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('suspend', 'Suspend'), ('unsuspend', 'Unsuspend'), ('delete', 'Delete'), ('other', 'Other')], max_length=20),
        ),
    ]
