# Generated by Django 5.1.2 on 2025-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_adminactionlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mobile_number', 'user_type'], name='users_custo_mobile__9e2678_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mobile_number', 'user_type', 'buyer_category'], name='users_custo_mobile__ae1dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'smart_seller')), fields=('mobile_number', 'user_type'), name='unique_seller_per_mobile'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'smart_buyer')), fields=('mobile_number', 'user_type', 'buyer_category'), name='unique_buyer_category_per_mobile'),
        ),
    ]
