# Generated by Django 5.2.7 on 2025-10-18 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_populate_anonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anonymous_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
