# Generated by Django 5.1.2 on 2025-10-21 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_anonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='anonymous_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]