# Generated by Django 5.1.2 on 2025-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_anonymous_id_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='channel',
            field=models.CharField(blank=True, choices=[('chat_smart_seller', 'Smart Seller'), ('chat_smart_buyer_shopkeeper', 'Smart Buyer - Shopkeeper'), ('chat_smart_buyer_mandi_owner', 'Smart Buyer - Mandi Owner'), ('chat_smart_buyer_community', 'Smart Buyer - Community')], db_index=True, max_length=64, null=True),
        ),
    ]
