# Generated by Django 5.1.2 on 2025-10-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_wishlist_and_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsessionitem',
            name='cart_session',
        ),
        migrations.AlterUniqueTogether(
            name='cartsessionitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartsessionitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartSession',
        ),
        migrations.DeleteModel(
            name='CartSessionItem',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
