# Generated by Django 5.1.2 on 2025-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], help_text='Payment method used', max_length=20),
        ),
    ]
