# Generated by Django 5.1.2 on 2025-10-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_razorpay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_awb_code',
            field=models.CharField(blank=True, help_text='Shiprocket AWB tracking code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_courier_id',
            field=models.CharField(blank=True, help_text='Selected courier company ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_courier_name',
            field=models.CharField(blank=True, help_text='Selected courier company name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, help_text='Shiprocket order ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full Shiprocket API response'),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, help_text='Shiprocket shipment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_status',
            field=models.CharField(blank=True, help_text='Shiprocket order status', max_length=50, null=True),
        ),
    ]
