# Generated by Django 5.1.2 on 2025-10-18 09:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shiprocket_awb_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_cancel_till',
            field=models.DateTimeField(blank=True, help_text='Last date/time till order can be cancelled', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee (1% of order value)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Razorpay payment gateway fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_pickup_scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled pickup date from Shiprocket', null=True),
        ),
        migrations.CreateModel(
            name='OrderCancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('change_of_mind', 'Change of Mind'), ('product_not_needed', 'Product Not Needed Anymore'), ('found_better_price', 'Found Better Price Elsewhere'), ('delivery_delay', 'Delivery Taking Too Long'), ('wrong_product', 'Ordered Wrong Product'), ('payment_issue', 'Payment Related Issue'), ('other', 'Other Reason')], help_text='Reason for cancellation', max_length=50)),
                ('reason_description', models.TextField(help_text='Detailed reason for cancellation')),
                ('request_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Refund Initiated'), ('refund_processed', 'Refund Processed'), ('rejected', 'Rejected'), ('cancelled', 'Request Cancelled')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded', max_digits=10)),
                ('razorpay_fee_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Razorpay fee to be deducted', max_digits=10)),
                ('platform_fee_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee to be deducted', max_digits=10)),
                ('final_refund_amount', models.DecimalField(decimal_places=2, help_text='Final amount after deductions', max_digits=10)),
                ('razorpay_refund_id', models.CharField(blank=True, help_text='Razorpay refund transaction ID', max_length=255, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the cancellation')),
                ('shiprocket_cancelled', models.BooleanField(default=False, help_text='Whether order was cancelled in Shiprocket')),
                ('shiprocket_cancellation_response', models.JSONField(blank=True, default=dict, help_text='Shiprocket cancellation API response')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_request', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Cancellation Request',
                'verbose_name_plural': 'Order Cancellation Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
