# Generated by Django 5.1.2 on 2025-10-21 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_can_cancel_till_order_platform_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Credit/Debit Card'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage charge to apply for this payment mode', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Mode Charge',
                'verbose_name_plural': 'Payment Mode Charges',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charge based on chosen payment mode', max_digits=10),
        ),
    ]
