# Generated by Django 5.1.2 on 2025-09-22 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal (100 kg)'), ('ton', 'Ton'), ('piece', 'Piece'), ('dozen', 'Dozen'), ('liter', 'Liter'), ('bag', 'Bag'), ('box', 'Box')], default='kg', max_length=20)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_buyers', models.CharField(choices=[('all', 'All Buyers'), ('mandi_owner', 'Mandi Owners'), ('shopkeeper', 'Shopkeepers'), ('community', 'Communities')], default='all', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_organic', models.BooleanField(default=False)),
                ('delivery_available', models.BooleanField(default=True)),
                ('pickup_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('farmer', models.ForeignKey(limit_choices_to={'user_type': 'smart_seller'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
