# Generated by Django 5.2.6 on 2025-09-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_buyers',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Set to False to unlist the product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum quantity a buyer must order.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity available for sale.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, help_text='The user who created this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='target_communities',
            field=models.BooleanField(default=False, help_text='Target Community Groups/Cooperatives.'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_mandi_owners',
            field=models.BooleanField(default=False, help_text='Target Mandi Owners/Wholesalers.'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_shopkeepers',
            field=models.BooleanField(default=False, help_text='Target Shopkeepers/Local Retailers.'),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, help_text='Specific variety (e.g., Heirloom Tomato).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed description, quality, and farming methods.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the produce (e.g., Tomato).', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price in Rupees per unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('QUINTAL', 'Quintal (100 Kg)'), ('TON', 'Metric Ton'), ('DOZEN', 'Dozen'), ('UNIT', 'Per Piece/Unit')], default='KG', help_text='The unit of measurement (e.g., KG, Quintal).', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
