# Generated by Django 5.1.2 on 2025-09-29 22:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_communities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_mandi_owners',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_shopkeepers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Current available quantity in quantity_unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='buyer_category_visibility',
            field=models.JSONField(blank=True, help_text='List of buyer categories allowed to view this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='High-level crop category (Vegetable, Fruit, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='crop',
            field=models.CharField(blank=True, help_text='Specific crop name (e.g., Brinjal)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/quality (e.g., A, B)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mandi_price_reference',
            field=models.JSONField(blank=True, help_text='Snapshot of mandi price', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='market_price_source',
            field=models.CharField(blank=True, help_text='Identifier for mandi price source when price_type=market_linked', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Free-form key/value data', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='INR', help_text='ISO 4217 currency code', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(default='fixed', help_text='fixed|negotiable|market_linked', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal (100 Kg)'), ('tonne', 'Metric Ton'), ('piece', 'Per Piece/Unit'), ('box', 'Box')], default='kg', help_text='Unit of quantity (kg, quintal, box, piece)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('pending_moderation', 'Pending Moderation')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Short product title (e.g., Brinjal - Hybrid (1kg))', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description, grower notes, variety'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, help_text='Variety or cultivar name', max_length=100, null=True),
        ),
    ]
