# Generated by Django 5.1.2 on 2025-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_min_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum quantity a buyer must order.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed Product', help_text='Name of the produce (e.g., Tomato).', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity available for sale.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='target_communities',
            field=models.BooleanField(default=False, help_text='Target Community Groups/Cooperatives.'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_mandi_owners',
            field=models.BooleanField(default=False, help_text='Target Mandi Owners/Wholesalers.'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_shopkeepers',
            field=models.BooleanField(default=False, help_text='Target Shopkeepers/Local Retailers.'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('QUINTAL', 'Quintal (100 Kg)'), ('TON', 'Metric Ton'), ('DOZEN', 'Dozen'), ('UNIT', 'Per Piece/Unit')], default='KG', help_text='The unit of measurement (e.g., KG, Quintal).', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer_category_visibility',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Detailed description, quality, and farming methods.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mandi_price_reference',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_price_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in Rupees per unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, help_text='Specific variety (e.g., Heirloom Tomato).', max_length=100, null=True),
        ),
    ]
