# Generated by Django 5.1.2 on 2025-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='High-level crop category (Vegetable, Fruit, etc.).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='crop',
            field=models.CharField(blank=True, help_text='Specific crop name (e.g., Brinjal).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/quality (e.g., A, B).', max_length=50, null=True),
        ),
    ]
