# Generated by Django 5.1.2 on 2025-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_product_crop_product_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
