# Generated by Django 5.1.2 on 2025-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_name_to_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark this as the primary image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the image if stored remotely', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d/'),
        ),
    ]
