# Generated by Django 5.1.2 on 2025-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_is_primary_productimage_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, help_text='City where the product is located', max_length=100, null=True),
        ),
    ]
