# Generated by Django 5.1.2 on 2025-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_address_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pexels_image_url',
            field=models.URLField(blank=True, help_text='Image URL fetched from Pexels API based on product title.', null=True),
        ),
    ]
