# Generated by Django 5.1.2 on 2025-10-14 14:29

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_pexels_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_path),
        ),
    ]
