# Generated by Django 5.1.2 on 2025-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pincode',
            field=models.CharField(default=110002, help_text='Pincode where the product is located', max_length=20),
            preserve_default=False,
        ),
    ]
