# Generated by Django 5.2.6 on 2025-10-17 19:36

from django.db import migrations


def create_categories_from_existing_data(apps, schema_editor):
    """
    Create Category objects from existing product category strings
    """
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    
    # Get all unique category names from existing products
    category_names = set()
    for product in Product.objects.exclude(category__isnull=True).exclude(category=''):
        category_names.add(product.category)
    
    # Create Category objects for each unique category name
    for category_name in category_names:
        category, created = Category.objects.get_or_create(
            name=category_name,
            defaults={
                'description': f'Auto-created category for {category_name}',
                'is_active': True
            }
        )
        if created:
            print(f"Created category: {category_name}")


def reverse_create_categories(apps, schema_editor):
    """
    Reverse the category creation (optional)
    """
    Category = apps.get_model('products', 'Category')
    # Only delete categories that were auto-created
    Category.objects.filter(description__startswith='Auto-created category').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_pincode'),
    ]

    operations = [
        migrations.RunPython(create_categories_from_existing_data, reverse_create_categories),
    ]
