# Generated by Django 5.2.6 on 2025-10-17 19:37

import django.db.models.deletion
from django.db import migrations, models


def populate_category_fk(apps, schema_editor):
    """
    Populate the new category_fk field based on existing category names
    """
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    
    for product in Product.objects.exclude(category__isnull=True).exclude(category=''):
        try:
            category = Category.objects.get(name=product.category)
            product.category_fk = category
            product.save()
        except Category.DoesNotExist:
            print(f"Warning: Category '{product.category}' not found for product {product.id}")


def reverse_populate_category_fk(apps, schema_editor):
    """
    Reverse the population (clear the foreign key field)
    """
    Product = apps.get_model('products', 'Product')
    Product.objects.update(category_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20251018_0106'),
    ]

    operations = [
        # Add the new foreign key field
        migrations.AddField(
            model_name='product',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_temp', to='products.category'),
        ),
        # Populate the new field with data
        migrations.RunPython(populate_category_fk, reverse_populate_category_fk),
    ]
