# Generated by Django 5.2.6 on 2025-10-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20251018_0107'),
    ]

    operations = [
        # Remove the old category CharField
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        # Rename category_fk to category and update the related_name
        migrations.RenameField(
            model_name='product',
            old_name='category_fk',
            new_name='category',
        ),
        # Update the field definition to match our target
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
