# Generated by Django 5.1.2 on 2025-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20251018_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text="Optional minimum quantity a buyer must order. If seller doesn't provide, default is 1.", max_digits=10),
        ),
    ]
